from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field

CONCEPT_ORDER = ["sequence", "conditions", "loops", "code_assembly"]


class LearningRecord(BaseModel):
    concept: str
    introduced: bool = False
    attempts: int = 0
    successes: int = 0
    first_try_successes: int = 0
    hints_used: int = 0
    revealed: bool = False
    difficulty: int = 1


class LearningProgress(BaseModel):
    """Source of truth for learning. Written ONLY by deterministic code."""
    stage: int = 0
    active_concept: str = "sequence"
    records: dict[str, LearningRecord] = Field(default_factory=dict)
    revealed: list[str] = Field(default_factory=list)
    next_difficulty: int = 1

    def record(self, concept: str) -> LearningRecord:
        if concept not in self.records:
            self.records[concept] = LearningRecord(concept=concept)
        return self.records[concept]


class PuzzleHint(BaseModel):
    hint: str
    nudge: str = ""


class LearningFrame(BaseModel):
    """Narrative framing generated by the Learning Agent (never the verdict)."""
    concept: str
    intro: str
    flavour: str = ""


class ConceptReveal(BaseModel):
    concept: str
    title: str
    explanation: str
    python_example: str
    world_analogy: str = ""


class PuzzlePrompt(BaseModel):
    puzzle_id: str
    concept: str
    title: str
    instructions: str
    difficulty: int
    spec: dict[str, Any]
    framing: str = ""
    max_ops: int = 0
    max_blocks: int = 0


class PuzzleResult(BaseModel):
    concept: str
    solved: bool
    reason: str = ""
    score: float = 0.0
    trace: dict[str, Any] = Field(default_factory=dict)


class InventionBlock(BaseModel):
    kind: str                      # move | turn_left | turn_right | repeat | if | glow
    times: int = 1
    condition: str = ""
    inner: str = ""


class Invention(BaseModel):
    name: str
    blocks: list[InventionBlock] = Field(default_factory=list)
    effect: str = ""
    created_turn: int = 0
